[[plugins]]
repo   = 'Shougo/unite.vim'

# unite.vim を読み込んだら一緒に読み込む
[[plugins]]
repo      = 'Shougo/neomru.vim'
on_source = ['unite.vim']

[[plugins]]
repo = "davidhalter/jedi-vim"
on_ft = ['python']

[[plugins]]
repo = "andviro/flake8-vim"
on_ft = ['python']

[[plugins]]
repo = "hynek/vim-python-pep8-indent"
on_ft = ['python']

[[plugins]]
repo = "jmcantrell/vim-virtualenv"
on_ft = ['python']

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']

[[plugins]]
repo = 'Shougo/neocomplete.vim'
insert = 1
