#/bin/bash
pip install numpy
pip install scipy
pip install matplotlib
pip install pandas
pip install mecab-python3
pip install requests
pip install requests_oauthlib
pip install tweepy
pip install twitter
pip install virtualenv
pip install virtualenvwrapper
pip install jupyter 
pip install xlrd 
pip install xlwt
pip install jupyterlab
pip install serverextension enable --py jupyterlab
pip install bash_kernel
pip install jupyter_contrib_nbextensions
jupyter contrib nbextensions install --user
pip install ipykernel
pip install scikit-learn
pip install seaborn
pip install prettyplotlib
pip install bokeh
pip install mpld3
pip install vispy
pip install pyproj
pip install smopy
pip install requests_oauthlib
pip install enum34
pip install networkx
pip install shapely
pip install descartes
pip install sympy
pip install ipythonblocks
pip install tables
pip install cython
pip install pyopencl
pip install scikit-image
pip install tensorflow
#pip install tensorflow-gpu
